// <auto-generated />
using Crudop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Crudop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231013085551_newupdate")]
    partial class newupdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Crudop.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Birthday")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StudentTable");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Age = 15,
                            Birthday = 2402,
                            Gender = "Female",
                            Name = "Reena",
                            PhoneNo = 758865700
                        },
                        new
                        {
                            Id = 4,
                            Age = 27,
                            Birthday = 3105,
                            Gender = "Female",
                            Name = "Savi",
                            PhoneNo = 854963705
                        },
                        new
                        {
                            Id = 5,
                            Age = 32,
                            Birthday = 2012,
                            Gender = "male",
                            Name = "Ishan",
                            PhoneNo = 793658946
                        },
                        new
                        {
                            Id = 6,
                            Age = 50,
                            Birthday = 1403,
                            Gender = "male",
                            Name = "Suresh",
                            PhoneNo = 154289653
                        },
                        new
                        {
                            Id = 9,
                            Age = 99,
                            Birthday = 2408,
                            Gender = "Female",
                            Name = "Rani",
                            PhoneNo = 832987458
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
